services:
  app:
    container_name: back-chat
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://johndoe:root@postgres:5432/mydb?schema=public"
      PORT: 5000
      HOST: 0.0.0.0
    ports:
      - 5000:5000
      - 8080:8080
    depends_on:
      - postgres
    networks:
     - app-network
  postgres:
    container_name: db-chat
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: "johndoe"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: mydb
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge